### ISSUE TITLE
How do you use the new PHP scraper?

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#116]
Looks like it's made to be hosted at ANU, is there a link somewhere that people can access it remotely for updates?

**Comment by samyex6** [comment]
Yeah it's using Partch as a remote server to run it. Right now you will need to set up on your own server to run it, because the code is currently suit for command-line use only, you can certainly execute it by simply visit the link `http://partch.anu.edu.au.virtual.anu.edu.au/~u5824077/scrape.php` that's served on my server though, however since there's a timeout setting in PHP so I don't think it will finish generating. (The average scraping time is around 6 minutes, the normal PHP timeout setting is 5 minutes.

I've tried to use write something that will directly trigger a background task, but it seems like crontab/exec is disabled on the Partch server, so I might try to write some front end panel thing to do that, so you don't need the terminal. It will look something like this:
![Image](http://i.imgur.com/njgLBqi.png)
