### ISSUE TITLE
ARAB2001

### ISSUE THREAD

**Issue by michaelh96** [catmanjan/anutimetable#140]
It is not letting me choose which Arabic conversation class I want on my timetable. It is also not listing the Wednesday 2-3 class at the CAIS lecture theatre.

**Comment by samyex6** [comment]
Umm sorry but I think ARAB2001 does not exist, which course are you actually referring to?

Anyway I have updated the timetable, so anything that's on the official timetable site should be listed on here as well. 

For the conversation class not choosable issue, please provide the correct course code so I can take a look (the issue is usually caused by the official data source not providing a proper group number though, for example: `Tutorial1 / 1` and `Tutorial1 / 2` belong to the same group but `Tutorial` and `Tutorial1 / 1` do not)

**Comment by michaelh96** [comment]
sorry, was referring to ARAB2011

**Comment by samyex6** [comment]
![screenshot from 2017-02-22 13-37-22](https://cloud.githubusercontent.com/assets/13520523/23211814/1ed77f4a-f904-11e6-921c-2c1213943242.png)

Too bad according to the official site they all belong to a different group..
