### ISSUE TITLE
Become a data provider for Timeweave

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#179]
I have been speaking with the people at Timeweave who have a neat app that people can use to view and share their timetable with friends (sort of like a social network/calendar)

The scraper matches their data requirements pretty closely, all we'd need is another scraper that determines the user's enrollment via isis

Some concerns:
- Is this a good idea?
- I don't think ANU would be happy with a server side scrape where timeweave has user credentials (need to talk to timeweave about having it done client side)

**Comment by EMorf** [comment]
Not sure if people would like to give access to ISIS which has everything from payment details to course grades. I personally wouldn't. People usually do 4 courses max, so it wouldn't be tedious to just ask them to input this information themselves.

I like the idea. I could use something like that myself, instead of sharing shitty screenshots through Facebook messenger and losing track of them.
