### ISSUE TITLE
Tutorials are broken again

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#21]
For example, see SCOM1001, if you select one tutorial it does not get rid of the rest.

This may be due to an error in the data itself, or the scraper.

**Comment by samyex6** [comment]
My one works fine..
I guess it's because SCOM1001 has both workshop and tutorial (not sure if they're the same thing)?

![1](https://cloud.githubusercontent.com/assets/13520523/11611605/91fb38a0-9c2a-11e5-98b5-344c2438ffe8.png)

![2](https://cloud.githubusercontent.com/assets/13520523/11611606/91fc878c-9c2a-11e5-8390-60a3dff4d788.png)
