### ISSUE TITLE
Some kind of bug...

### ISSUE THREAD

**Issue by tail-recursion** [catmanjan/anutimetable#217]
I've tested on Safari, Mozilla and Chrome. Same thing. When I first load up the page it prompts me with 'a new version is available,' I'm guessing I have an old version of the website cached? I click okay. Now if I try to add a course, clicking the add button does nothing. If I click the clear button I am now able to add courses normally.

**Comment by williamshen-nz** [comment]
Looks like it's because `Courses.courses` is being set to `{}` instead of `[]` [here](https://github.com/catmanjan/anutimetable/blob/master/js/timetable.js#L661). [`indexOf`](https://github.com/catmanjan/anutimetable/blob/master/js/timetable.js#L386) when adding a course assumes a list, not a hashmap/dictionary so an exception will be thrown.

There really should be tests to catch out these sorts of problems.

**Comment by samyex6** [comment]
It should be fixed now, I've also added a test directory to work on some small tests
