### ISSUE TITLE
Add support for half hour courses

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#28]
As noted in the known issues, some classes go for 90 minutes and with the current system, this would lead to clashes.

**Comment by samyex6** [comment]
Will need to think about the way of displaying it without looking messy..

Using the current template, if we divide an hour into two half-hours, then a 2-hour class starting say from 1:30 to 3:30 will display as four blocks which look terrible.
Also if other classes are in the same time slot, it will become something confusing like:
1:30 [class 1] 
        [class 2]
        ----------
2:00 [class 1] 
        [class 2] 
        ----------
2:30 [class 1]
            ...

If we use the official way which each class as a single block then we need to truncate visible text otherwise it'll overflow.

**Comment by samyex6** [comment]
https://rawgit.com/samyex6/anutimetable/experimental/

This is a preview, currently it's not fully functional:
1. Only recover from the save works fine.
2. When you delete a course or sometimes add a course, the table will be broken (but it'll be fixed after refreshing)
3. If you add too many courses the table will start to overflow (need to add a course number limitation. i.e. 6).

Dealing with row/colspan is such a pain in the ass ;-;

**Comment by catmanjan** [comment]
Do you think what's currently in production is good enough for me to close this issue?

**Comment by samyex6** [comment]
yeah i think the problem this issue targeted was resolved. the tutorial issue should be separate from this.
