### ISSUE TITLE
COMP2710 (Laptop Ensemble) and COMP2710 (Cyber Security) break the new scraper

### ISSUE THREAD

**Issue by paked** [catmanjan/anutimetable#332]
Would assume it has something to do with the way the names show up in this list (do we have a regex which is failing here?)

![Screenshot_20200212_102622](https://user-images.githubusercontent.com/8407370/74289077-39db9300-4d82-11ea-90df-1c6a7861f7af.png)

**Comment by paked** [comment]
... the plot thickens: these course names show in in timetable.json.

something on the client side must be broken!

**Comment by catmanjan** [comment]
@paked I did see that, although the course is in timetable.json the class associated with it are not -COMP2710_S1-PraA/01 is missing

Either those classes

**Comment by samyex6** [comment]
This is because `courseNameElement.val().split('-')[0].toUpperCase().trim()` converted the whole string before _S1 into capital cases, however when selecting courses it uses the string with normal cases to locate, therefore the course can't be found.

It should be fixed by now, 

I forgot if this upper case conversion is intentional though... so for now I just added another conversion at line 414 
```courseName = courseName.replace(/(\s\w)(\w+)/g, (m, a, b) => a + b.toLowerCase());```
so I don't break anything, the simpler solution (removing toUpperCase()) can be applied later once confirmed safe,

**Comment by BishopOfTurkey** [comment]
This seems to to be working
